services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      API_PROXY_TARGET: http://api:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run server
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules